install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- mkdir _build
- cd paper
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex -output-directory ../_build ms.tex