sudo: required
language: generic
services: docker

script:
  - docker pull dxjoke/tectonic-docker
  - .ci/gen-hogg.sh
  - docker run --mount src=$TRAVIS_BUILD_DIR/paper,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --print --keep-intermediates --reruns 0 ms.tex ; bibtex ms ; tectonic ms.tex"
  - docker run --mount src=$TRAVIS_BUILD_DIR/paper,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --print --keep-intermediates --reruns 0 ms_hogg.tex ; bibtex ms_hogg ; tectonic ms_hogg.tex"
  - source .ci/build-paper.sh
